"""
Django settings for my_hospaital project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# ================================================
#             BASE DIRECTORY
# ================================================
BASE_DIR = Path(__file__).resolve().parent.parent

# ================================================
#             SECURITY
# ================================================
SECRET_KEY = 'django-insecure-ix5u=(c15@xga48ay_l^s@n3uyu9$g-@=i+y=)mb2te^-f3u^='
DEBUG = True
ALLOWED_HOSTS = ['*']

# ================================================
#             APPLICATION DEFINITION
# ================================================
INSTALLED_APPS = [
    'django_daisy',  # custom app
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'accounts.apps.AccountsConfig',
    
    # Project apps (في الترتيب الصحيح حسب التبعيات)
    'core.apps.CoreConfig',              # الأساسية أولاً
    'students.apps.StudentsConfig',      # الطلاب
    'housing.apps.HousingConfig',        # المباني والغرف
    'staff.apps.StaffConfig',            # الموظفين
    'bookings.apps.BookingsConfig',      # الحجوزات (تعتمد على students + housing)
    'payments.apps.PaymentsConfig',      # المدفوعات (تعتمد على students + core)
    'support.apps.SupportConfig',        # الدعم (تعتمد على students + housing + staff)
    'dashboard.apps.DashboardConfig',    # لوحة التحكم (تستخدم كل شيء)
    
]

MIDDLEWARE = [
     'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # CsrfViewMiddleware معطل مؤقتًا لتجاوز 403 admin في التطوير
     'django.middleware.csrf.CsrfViewMiddleware',  
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'my_hospaital.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',  # مهم للـ admin
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.user_role',
            ],
        },
    },
]

WSGI_APPLICATION = 'my_hospaital.wsgi.application'

# ================================================
#             DATABASE
# ================================================
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ================================================
#             PASSWORD VALIDATION
# ================================================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# ================================================
#             INTERNATIONALIZATION
# ================================================
LANGUAGE_CODE = 'ar'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True

# ================================================
#             STATIC FILES
# ================================================
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/portal/'
LOGOUT_REDIRECT_URL = '/'


# ================================================
#             DEFAULT AUTO FIELD
# ================================================
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ================================================
#             CSRF & SESSION (تجاوز مؤقت)
# ================================================
# يسمح بالوصول المباشر للـ /admin/ في التطوير
CSRF_COOKIE_SECURE = False
SESSION_COOKIE_SECURE = False
CSRF_USE_SESSIONS = False

# Trusted origins (لتجنب مشاكل CSRF عند استخدام POST)
CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:8000",
    "http://localhost:8000",
    "http://127.0.0.1:3000",
    "http://localhost:3000",
]

# ================================================
#             ADDITIONAL SETTINGS (يمكن توسعتها لاحقًا)
# ================================================
# هنا يمكن إضافة أي إعدادات أخرى للتطوير أو التطبيقات المخصصة
# مثل إعدادات البريد، إعدادات cache، إعدادات logging، ...الخ

