# Generated by Django 5.2.8 on 2026-02-17 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method_name', models.CharField(max_length=50, unique=True, verbose_name='طريقة الدفع')),
            ],
            options={
                'verbose_name': 'طريقة الدفع',
                'verbose_name_plural': 'طرق الدفع',
                'db_table': 'core_payment_method',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(max_length=50, unique=True, verbose_name='العمل الوظيفي')),
            ],
            options={
                'verbose_name': 'العمل الوظيفي',
                'verbose_name_plural': 'الأعمال الوظيفية',
                'db_table': 'core_role',
            },
        ),
    ]
