# Generated by Django 5.2.4 on 2025-09-27 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': 'حجز', 'verbose_name_plural': 'الحجوزات'},
        ),
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'مبنى', 'verbose_name_plural': 'المباني'},
        ),
        migrations.AlterModelOptions(
            name='complaint',
            options={'verbose_name': 'شكوى', 'verbose_name_plural': 'الشكاوى'},
        ),
        migrations.AlterModelOptions(
            name='maintenance',
            options={'verbose_name': 'صيانة', 'verbose_name_plural': 'الصيانات'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'دفع', 'verbose_name_plural': 'المدفوعات'},
        ),
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'طريقة الدفع', 'verbose_name_plural': 'طرق الدفع'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': 'العمل الوظيفي', 'verbose_name_plural': 'الأعمال الوظيفية'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'verbose_name': 'غرفة', 'verbose_name_plural': 'الغرف'},
        ),
        migrations.AlterModelOptions(
            name='staff',
            options={'verbose_name': 'موظف', 'verbose_name_plural': 'الموظفين'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'طالب', 'verbose_name_plural': 'الطلاب'},
        ),
        migrations.AlterField(
            model_name='assignment',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.room', verbose_name='الغرفة'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='start_date',
            field=models.DateField(verbose_name='تاريخ البداية'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('Active', 'نشطة'), ('Completed', 'مكتملة'), ('Cancelled', 'ملغاة')], default='Active', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.student', verbose_name='الطالب'),
        ),
        migrations.AlterField(
            model_name='building',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='الموقع'),
        ),
        migrations.AlterField(
            model_name='building',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='اسم المبنى'),
        ),
        migrations.AlterField(
            model_name='building',
            name='total_floors',
            field=models.PositiveIntegerField(verbose_name='عدد الطوابق'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.TextField(verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.staff', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'قيد الانتظار'), ('In Progress', 'قيد التنفيذ'), ('Resolved', 'تم الحل')], default='Pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.student', verbose_name='الطالب'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='description',
            field=models.TextField(verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.room', verbose_name='الغرفة'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ الصيانة'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.staff', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='status',
            field=models.CharField(choices=[('Pending', 'قيد الانتظار'), ('In Progress', 'قيد التنفيذ'), ('Completed', 'تم الانتهاء')], default='Pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.paymentmethod', verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(verbose_name='تاريخ الدفع'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.student', verbose_name='الطالب'),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='method_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='طريقة الدفع'),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='العمل الوظيفي'),
        ),
        migrations.AlterField(
            model_name='room',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='رقم الشقة'),
        ),
        migrations.AlterField(
            model_name='room',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.building', verbose_name='المبنى'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveIntegerField(verbose_name='السعة'),
        ),
        migrations.AlterField(
            model_name='room',
            name='current_capacity',
            field=models.PositiveIntegerField(default=0, verbose_name='السعة الحالية'),
        ),
        migrations.AlterField(
            model_name='room',
            name='floor_number',
            field=models.IntegerField(verbose_name='الطابق'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(max_length=10, verbose_name='رقم الغرفة'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.role', verbose_name='الوظيفة'),
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(verbose_name='تاريخ الميلاد'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'ذكر'), ('F', 'أنثى')], max_length=1, verbose_name='الجنس'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(max_length=15, unique=True, verbose_name='رقم الهاتف'),
        ),
    ]
