# Generated by Django 5.2.8 on 2025-11-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_assignment_options_alter_building_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='admin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='المسؤول'),
        ),
    ]
