# Generated by Django 5.2.8 on 2026-02-17 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('housing', '0001_initial'),
        ('staff', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('status', models.CharField(choices=[('Pending', 'قيد الانتظار'), ('In Progress', 'قيد التنفيذ'), ('Resolved', 'تم الحل')], default='Pending', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to='staff.staff', verbose_name='الموظف')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='students.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'شكوى',
                'verbose_name_plural': 'الشكاوى',
                'db_table': 'support_complaint',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='الوصف')),
                ('status', models.CharField(choices=[('Pending', 'قيد الانتظار'), ('In Progress', 'قيد التنفيذ'), ('Completed', 'تم الانتهاء')], default='Pending', max_length=20, verbose_name='الحالة')),
                ('priority', models.CharField(choices=[('Low', 'منخفضة'), ('Medium', 'متوسطة'), ('High', 'عالية')], default='Medium', max_length=10, verbose_name='الأولوية')),
                ('scheduled_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الصيانة')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإنجاز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_requests', to='housing.room', verbose_name='الغرفة')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance', to='staff.staff', verbose_name='الموظف')),
            ],
            options={
                'verbose_name': 'صيانة',
                'verbose_name_plural': 'الصيانات',
                'db_table': 'support_maintenance',
                'ordering': ['-created_at'],
            },
        ),
    ]
