# Generated by Django 5.2.8 on 2026-02-17 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم المبنى')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='الموقع')),
                ('total_floors', models.PositiveIntegerField(verbose_name='عدد الطوابق')),
                ('admin', models.CharField(blank=True, max_length=100, null=True, verbose_name='المسؤول')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'مبنى',
                'verbose_name_plural': 'المباني',
                'db_table': 'housing_building',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=10, verbose_name='رقم الغرفة')),
                ('apartment_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='رقم الشقة')),
                ('floor_number', models.IntegerField(verbose_name='الطابق')),
                ('capacity', models.PositiveIntegerField(verbose_name='السعة')),
                ('current_capacity', models.PositiveIntegerField(default=0, verbose_name='السعة الحالية')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='السعر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='housing.building', verbose_name='المبنى')),
            ],
            options={
                'verbose_name': 'غرفة',
                'verbose_name_plural': 'الغرف',
                'db_table': 'housing_room',
                'unique_together': {('building', 'room_number')},
            },
        ),
    ]
